// AppDbContext.cs
// EF Core's "connection manager" between C# code and the SQL Server database.
// This is what lets you write LINQ queries in C# instead of raw SQL.
//
// This file would normally be auto-generated by the scaffold command (see CLAUDE.md step 6).
// The connection string is configured in Program.cs (read from appsettings.json), never hardcoded here.
// The "partial" keyword allows the scaffold to regenerate this file without losing any custom code
// you add in a separate partial class file.

using Microsoft.EntityFrameworkCore;

namespace timezone_manager.Models;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

    // Represents the DeliveryRecords table. Use this to query or add rows.
    // Example: db.DeliveryRecords.Where(r => r.Plant == "Stockholm").ToList()
    public virtual DbSet<DeliveryRecord> DeliveryRecords { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DeliveryRecord>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Plant).HasMaxLength(50);
            entity.Property(e => e.Material).HasMaxLength(100);
            entity.Property(e => e.TimestampUtc).HasColumnType("datetime2(7)");
            entity.Property(e => e.SubmitterTimezone).HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    // This partial method exists so the scaffold can add extra configuration without
    // touching the auto-generated code above.
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
