// DeliveryRecord.cs
// The C# class that maps to the DeliveryRecords table in SQL Server.
// EF Core uses this class to read and write rows — each property maps to a column.
//
// This file would normally be auto-generated by the "dotnet ef dbcontext scaffold" command
// (see CLAUDE.md setup step 6). It is written manually here so the project compiles without
// needing a live database connection. Re-running the scaffold command with --force will
// regenerate it from the actual table definition.

namespace timezone_manager.Models;

public partial class DeliveryRecord
{
    public int Id { get; set; }
    public string DeliveryNumber { get; set; } = null!;
    public string Plant { get; set; } = null!;
    public string Material { get; set; } = null!;

    // Stored as UTC — never local time. Always UTC in the database.
    public DateTime TimestampUtc { get; set; }

    // IANA timezone ID of whoever submitted this record, e.g. "Europe/Stockholm" or "America/Sao_Paulo".
    // Captured automatically from the browser — the user never types this.
    public string SubmitterTimezone { get; set; } = null!;
}
